defmodule PastimesReg.Activities.ActivitiesOption do
  @available_activities [
    "Backcountry Touring",
    "Backpacking",
    "Badminton",
    "Baseball",
    "Basketball",
    "Beach Volleyball",
    "Bikepacking",
    "Bird Watching",
    "BMX",
    "Boating",
    "Bocce Ball",
    "Bouldering",
    "Camping",
    "Canoeing",
    "Canyoneering",
    "Caving",
    "Cornhole",
    "Croquet",
    "Cross Country Skiing",
    "Cyclocross",
    "Dirt Biking",
    "Disc Golf",
    "eMountain Biking",
    "Equestrian",
    "Fat Biking",
    "Fishing",
    "Fitness Training",
    "Fly Fishing",
    "Football",
    "Foraging",
    "Freediving",
    "Geocaching",
    "Golf",
    "Gravel Biking",
    "Gymnastics",
    "Hand Ball",
    "Hiking",
    "Hockey",
    "Hunting",
    "Ice Climbing",
    "Ice Skating",
    "Kadima",
    "Kan Jam",
    "Kayaking",
    "Kickball",
    "Kitesurfing",
    "Kubb",
    "Lacrosse",
    "Martial Arts",
    "Mountain Biking",
    "Mountaineering",
    "Obstacle Course",
    "Off Roading",
    "Outdoor Photography",
    "Paddleboarding",
    "Paragliding",
    "Parkour",
    "Pickleball",
    "Ping Pong",
    "Plen Air Painting",
    "Racquetball",
    "Rafting",
    "Road Cycling",
    "Rock Climbing",
    "Rock Hounding",
    "Roller Skating",
    "Roller Skiing",
    "Rugby",
    "Running",
    "Sailing",
    "Scuba Diving",
    "Shooting Sports",
    "Skateboarding",
    "Skiing",
    "Skydiving",
    "Slackline",
    "Snowboarding",
    "Snowkiting",
    "Snowmobiling",
    "Snowshoeing",
    "Soccer",
    "Softball",
    "Spearfishing",
    "Spike Ball",
    "Strength Training",
    "Surfing",
    "Swimming",
    "Tennis",
    "Trail Running",
    "Triathlon",
    "Ultimate Frisbee",
    "Volleyball",
    "Volunteering"
  ]

  @spec activity_options :: [<<_::24, _::_*8>>, ...]
  def activity_options, do: @available_activities
end
